name: Linter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Install blender
#      run: |
#        python3.7 -m pip install --upgrade pip wheel future-fstrings
#        python3.7 -m pip install bpy --no-binary :all:
    - name: Analysing the code with pylint
      run: |
        pylint `find . -name "*.py"` --rcfile=.pylintrc --threshold 5